# Generated by Django 4.1.6 on 2024-04-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_user_login_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_login",
            name="email",
        ),
    ]
