# Generated by Django 5.1.3 on 2025-07-26 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="姓名")),
                ("age", models.IntegerField(verbose_name="年龄")),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="收入"
                    ),
                ),
                ("tel", models.CharField(max_length=32, verbose_name="电话")),
                ("create_time", models.DateField(verbose_name="入职时间")),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(0, "男"), (1, "女")], verbose_name="性别"
                    ),
                ),
                ("email", models.CharField(max_length=20, verbose_name="邮箱")),
            ],
        ),
        migrations.CreateModel(
            name="work_time",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateField(max_length=64, verbose_name="值班时间")),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.userinfo",
                        verbose_name="值班人员",
                    ),
                ),
            ],
        ),
    ]
