# Generated by Django 4.1.6 on 2024-04-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="email",
            field=models.CharField(default=0, max_length=20, verbose_name="邮箱"),
            preserve_default=False,
        ),
    ]
