# Generated by Django 4.1.6 on 2024-04-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="value",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tem", models.FloatField(verbose_name="温度")),
                ("humidity", models.FloatField(verbose_name="湿度")),
                ("time", models.DateTimeField(verbose_name="时间")),
            ],
        ),
    ]
