# Generated by Django 4.1.6 on 2024-04-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Statistics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="value",
            name="time",
            field=models.DateTimeField(default=1, verbose_name="时间"),
            preserve_default=False,
        ),
    ]
